# Generated by Django 3.2.6 on 2021-09-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_alter_newsprise_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HodimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=250)),
                ('lavozim', models.CharField(max_length=250)),
                ('birth_day', models.DateField()),
                ('tg_joyi', models.CharField(max_length=150)),
                ('oqigan_joyi', models.CharField(max_length=150)),
                ('ilmiy_darajasi', models.CharField(max_length=150)),
                ('ish_tajribasi', models.SmallIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='image/')),
            ],
        ),
        migrations.DeleteModel(
            name='XodimModel',
        ),
    ]
