version: '3'

services:
  uzundb:
    container_name: uzundb
    image: postgres
    environment:
      POSTGRES_DB: db_uzun
      POSTGRES_USER: uzunuser
      POSTGRES_PASSWORD: uzunpass
    volumes:
      - postgres_data:/var/lib/postgresql/datauzun/
    ports:
      - "5432:5432"
  uzunweb:
    container_name: uzun
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - uzundb
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
